# Generated by Django 5.2.1 on 2025-06-01 19:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_j9jrqh', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
