# Generated by Django 5.2.1 on 2025-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_paymenthistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='tnx_id',
            field=models.CharField(max_length=100),
        ),
    ]
