# Generated by Django 5.2.1 on 2025-06-01 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_descriptions_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='total_product',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
