# Generated by Django 5.2.1 on 2025-06-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'created_at'},
        ),
    ]
