# Generated by Django 5.1.7 on 2025-06-25 16:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
