# Generated by Django 5.2.1 on 2025-06-26 17:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productreview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dvyz3blnz/image/upload/v1750957571/images_qr0fbd.jpg', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
